const PERMISSIONS = {
  DASHBOARD: 'dashboard',
  SHOW_QUOTATIONS: 'show_quotations',
  CHANGE_STATUS_QUOTATIONS: 'change_status_quotations',
}

const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  DISTRIBUTOR: 'distributor',
  CUSTOMER: 'customer',
};

const ROLES_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.SHOW_QUOTATIONS,
    PERMISSIONS.CHANGE_STATUS_QUOTATIONS,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.SHOW_QUOTATIONS,
    PERMISSIONS.CHANGE_STATUS_QUOTATIONS,
  ],
  [ROLES.DISTRIBUTOR]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.SHOW_QUOTATIONS,
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.DASHBOARD,
  ],
};

module.exports = {
  PERMISSIONS,
  ROLES,
  ROLES_PERMISSIONS,
};
